Se ha añadido un plugin para email
iti-ict/wakamiti pull request #153
Opened 2023-06-01 11:30 UTC by adronmarsh

2023-06-02 06:42 UTC, linesta-iti requested changes

2023-06-02 06:42 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/pom.xml
> +            <groupId>org.testng</groupId>
TestNG es un framework de testing alternativo a JUnit, no se suelen usar juntos, me extraña que te haya hecho falta para esto

2023-06-02 06:42 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/pom.xml
> +                <groupId>org.openjfx</groupId>
Esto parece un lanzador de aplicacion JavaFX (que es como un conjunto de librerias para hacer aplicaciones de escritorio con ventanas y demas). Imagino que todo esto lo habra generado IntelliJ al pedirle un nuevo proyecto, pero tendremos que quitarlo del pom.

2023-06-02 06:42 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/java/es/iti/wakamiti/email/EmailStepContributor.java
> +    private static String protocol;
No deberian ser campos estaticos, cada escenario tendra su propia instancia de esta clase

2023-06-02 06:42 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/java/es/iti/wakamiti/email/EmailStepContributor.java
> +    private static void processMessages(Message[] messages, org.w3c.dom.Document xmlDoc) throws Exception {
Si la parte que tiene la chicha en si, se hace mucho mas compleja y se traduce en muchas lineas de codigo, igual se podria considerar abstraerla un poco y sacarla a una clase nueva fuera, algo en plan EmailReader, de forma que el StepContributor se centre en definir los pasos y en llamar al reader.

2023-06-05 08:40 UTC, linesta-iti requested changes

2023-06-05 08:40 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/resources/iti_wakamiti_wakamiti-email.properties
> +mail.auth.saveXml=the emails.xml file containing the email data is saved.
el nombre del fichero xml podria estar parametrizado

2023-06-05 08:40 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/resources/iti_wakamiti_wakamiti-email_es.properties
> +mail.auth.saveXml=se guarda el archivo emails.xml que contiene los datos de los correos
el nombre del fichero xml podria estar parametrizado

2023-06-05 08:40 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/resources/iti_wakamiti_wakamiti-email.properties
> +mail.server.protocol=the server's network protocol is {text}.
los pasos son un poco genericos, hay que pensar que este plugin convivira con otros plugins (por ejemplo el de rest) y que se deberia poder distinguir el paso univocamente.

Se podria cambiar  'the server's network protocol' por 'the email server protocol' , 
'the user is' por 'the email address is',  'the password is' por 'the email password is', 
y asi sucesivamente, para diferenciarlo mas y asegurarnos que no entrara en conflicto con los pasos de otros 
plugins.

2023-06-05 08:40 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/java/es/iti/wakamiti/email/EmailReader.java
> +    @Step(value = "mail.auth.process")
sobra marcar este metodo como @Step, como es una clase auxiliar no afecta en nada

2023-06-05 08:40 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/resources/iti_wakamiti_wakamiti-email.properties
> +mail.server.protocol=the server's network protocol is {text}.
Los pasos no deberian acabar en punto (no hay ningun motivo en concreto, pero en todos los ejemplos de Gherkin que he visto hasta la fecha, nadie los acaba con un punto, y en el resto de plugins tampoco lo hacemos, asi que por mantener la consistencia, mejor quitarlo)

2023-06-05 08:40 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/java/es/iti/wakamiti/email/EmailStepContributor.java
> +    @Step(value = "mail.auth.session")
Los metodos marcados con @Step no pueden ser privados, y ademas no pueden aceptar cualquier parametro, ha de ajustarse a el/los parametro/s declarados en el paso (en el .properties)

2023-06-05 09:37 UTC, linesta-iti commented on wakamiti-plugins/wakamiti-email/src/main/java/es/iti/wakamiti/email/EmailStepContributor.java
> +    private Session getSession(Properties properties) {
public void setSession() {
     this.session = Session.getInstance( getMailProperties(this.user,...))
}

2023-06-06 08:49 UTC, mgalbis commented
Hay que tener en cuenta que los emails llegan de forma asíncrona. En este sentido, el plugin debería funcionar de forma similar al plugin amqp, con la clase `await` y un timeout configurable para esperar la recepción de los mensajes.

2023-09-15 05:50 UTC, closed without merging